import java.io.*;
import java.util.*;
import java.util.concurrent.*;

public class ComplexDemo {
    public static void main(String[] args) {
        System.out.println("Starting Complex Java Program...");

        // Step 1: Create a thread pool
        ExecutorService executor = Executors.newFixedThreadPool(3);

        // Step 2: Submit tasks to the thread pool
        for (int i = 1; i <= 3; i++) {
            int taskId = i;
            executor.submit(() -> {
                System.out.println("Task " + taskId + " is running on thread: " + Thread.currentThread().getName());
                performFileOperation(taskId);
            });
        }

        // Step 3: Shutdown the executor
        executor.shutdown();
        try {
            executor.awaitTermination(1, TimeUnit.MINUTES);
        } catch (InterruptedException e) {
            System.err.println("Tasks interrupted.");
        }

        System.out.println("All tasks completed.");
    }

    private static void performFileOperation(int taskId) {
        String fileName = "task_" + taskId + ".txt";
        try {
            // Write to a file
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
                writer.write("This is Task " + taskId + "'s file.");
                writer.newLine();
                writer.write("Generated by thread: " + Thread.currentThread().getName());
            }

            // Read from the file
            try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
                System.out.println("Contents of " + fileName + ":");
                String line;
                while ((line = reader.readLine()) != null) {
                    System.out.println(line);
                }
            }
        } catch (IOException e) {
            System.err.println("Error handling file " + fileName + ": " + e.getMessage());
        }
    }
}